replace connect modal for connect button on new position page
invariant-labs/webapp-azero pull request #310
Opened 2024-09-19 10:11 UTC by zielvna

2024-09-19 10:28 UTC, p6te reviewed
![image](https://github.com/user-attachments/assets/b6da5ca8-c72a-48f2-9b58-63b21967484a)
![image](https://github.com/user-attachments/assets/1fad3d1c-747e-48a4-b09e-bbf4f8c96c14)
connect wallet button is too high

2024-09-19 10:35 UTC, p6te commented on src/components/NewPosition/DepositSelector/style.ts
> +      height: '48px !important',
is it possible to not use `!important`?

2024-09-19 10:46 UTC, wojciech-cichocki requested changes
Jumping position of button: "Connect wallet" and "Add position"
[Screencast from 19.09.2024 12:44:52.webm](https://github.com/user-attachments/assets/220c1fbf-7f13-4451-b95d-5afd02b82c52)

2024-09-21 15:30 UTC, wojciech-cichocki requested changes
The placeholder inside the input token amount should appear like this when the wallet is disconnected: `Balance: - USDC`

It should be similar to this, but **with the selected token ticker**:
![image](https://github.com/user-attachments/assets/5d44cbb2-bbc4-4cf0-adc6-0214dccf0d2c)

Instead of the current version:
![image](https://github.com/user-attachments/assets/9655b6e7-426b-4f74-b671-798cdcf7b99e)

2024-09-22 20:47 UTC, wojciech-cichocki requested changes
Is there a need to trigger a loader for the token balance in case the wallet is disconnected? There should always be a -" value:
[Screencast from 22.09.2024 22:44:52.webm](https://github.com/user-attachments/assets/97ef9bd5-5e73-405f-97fc-311a7be45123)

2024-09-23 06:31 UTC, p6te approved these changes

2024-09-23 12:27 UTC, p6te approved these changes

2024-09-23 12:56 UTC, wojciech-cichocki requested changes
Bug with token balances after triggering refresh:
[Screencast from 23.09.2024 14:50:20.webm](https://github.com/user-attachments/assets/21081cd9-863a-491b-ba4b-3778fe497bbf)

2024-09-24 08:48 UTC, p6te approved these changes

2024-09-24 08:57 UTC, wojciech-cichocki approved these changes

2024-09-24 08:58 UTC, merged