trim zeros, update button loader
invariant-labs/webapp-azero pull request #347
Opened 2024-10-17 11:06 UTC by p6te

- trim zeros in exchange and deposit inputs
- update animated button during loading
- update metadata logo image

2024-10-17 13:34 UTC, zielvna approved these changes

2024-10-18 06:02 UTC, wojciech-cichocki requested changes
When I select 'MAX' in the ETH wallet:
![image](https://github.com/user-attachments/assets/2ed6e47b-85a7-440a-8070-90aa5da100ee)

2024-10-18 06:13 UTC, wojciech-cichocki requested changes
metadata logo
![image](https://github.com/user-attachments/assets/8c45191f-1e6c-4d31-b446-60096baa53e9)

2024-10-20 15:15 UTC, wojciech-cichocki requested changes
metatags not works in my case:
![image](https://github.com/user-attachments/assets/26e10c43-bbce-44c7-a0db-953057d90f11)

2024-10-22 03:10 UTC, wojciech-cichocki approved these changes

2024-10-22 05:51 UTC, merged